### ISSUE TITLE
The sample does not demonstrate use of ADAL JS without Angular

### ISSUE THREAD

**Issue by vibronet** [AzureADSamples/SinglePageApp-AngularJS-DotNet#11]
The sample does not demonstrate use of ADAL JS without Angular.
The team has in the backlog the creation of a new sample showing direct ADAL JS use.

**Comment by panesofglass** [comment]
@vibronet, do you happen to have a blog post or anything? We are trying to use ADAL JS without Angular and need it imminently. :)

**Comment by vibronet** [comment]
We're working on a sample, it's in review hence that should be ready soon - but I can't give you an exact date yet. In the meanwhile: take a look at the last comment in the comment thread of http://channel9.msdn.com/Shows/Web+Camps+TV/AngularJS-Module-for-Microsoft-Azure-Active-Directory-Authentication - it might give some suggestions. Thanks for your patience!

**Comment by panesofglass** [comment]
Excellent! Thanks, Vittorio!

**Comment by dstrockis** [comment]
https://github.com/AzureADSamples/SinglePageApp-jQuery-DotNet
