### ISSUE TITLE
sessionStorage does not save state when using IE11

### ISSUE THREAD

**Issue by xqiu** [AzureADSamples/SinglePageApp-AngularJS-DotNet#14]
I can get the sample work when using chrome and IE10 mode.  But not in latest IE11 with windows 8.1 (with latest update as of today, 2/24/2015), when sessionStorage is used by default.  I can get it work if I setup localStorage.  I'm not sure if it's because IE11 has a bug with sessionStorage or the login redirect did something tricky when it's IE11.

**Comment by dstrockis** [comment]
This should only be the case when running in IE on localhost.  If you deploy to Azure Websites, for instance, you should not see this problem.  For development, I recommend using chrome or enabling localStorage as you've discovered.
