### ISSUE TITLE
Wont authenticate to Azure AD

### ISSUE THREAD

**Issue by nigel-dewar** [AzureADSamples/SinglePageApp-AngularJS-DotNet#15]
Hi This example does not work.

It makes it to azure authentication page where one enters user id and password, but fails after that with very unhelpful correlation id.

Is this example missing something. I have other examples working fine from this AZ tenant, for instance using Office 365 expense manager example works just fine. So my creds are correct, I have double checked them several times over.

Have things changed on the microsoft azure end, and is this example missing the actual app key? I noticed that you enter the tenant, the client id, but the app key is not included? Could this be the case?

regardless, it does not work.

**Comment by dstrockis** [comment]
Hi Nigel, could your provide the details of the error you see on the sign in page?

**Comment by ThorstenHans** [comment]
Do you get any error on the resulting page? double-check the browser console, normally Azure AD writes a more detailed information below the correlation id directly on the error page.

**Comment by nigel-dewar** [comment]
I managed to get this working thanks. It must have been because of my VS version, because once I updated to VS 2013 update 4, all was well.  Thanks for your help
