### ISSUE TITLE
Works perfect in IE, but fails in Chrome? and database fails fullstop

### ISSUE THREAD

**Issue by nigel-dewar** [AzureADSamples/SinglePageApp-AngularJS-DotNet#16]
Works perfect in IE, but fails in Chrome?
Any ideas as to why this might be?

Second, when trying to load Todos list, it pumps out this error on the screen.

{"Message":"An error has occurred.","ExceptionMessage":"An exception occurred while initializing the database. See the InnerException for details.","ExceptionType":"System.Data.DataException","StackTrace":" at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)\r\n at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()\r\n at System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)\r\n at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)\r\n at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)\r\n at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()\r\n at System.Data.Entity.Internal.InternalContext.Initialize()\r\n at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)\r\n at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()\r\n at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()\r\n at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()\r\n at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)\r\n at TodoSPA.Controllers.TodoListController.Get() in c:\\temp\\ADAL.js\\SinglePageApp-AngularJS-DotNet-master\\TodoSPA\\Controllers\\TodoListController.cs:line 23\r\n at lambda_method(Closure , Object , Object[] )\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"The underlying provider failed on Open.","ExceptionType":"System.Data.Entity.Core.EntityException","StackTrace":" at System.Data.Entity.Core.EntityClient.EntityConnection.Open()\r\n at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)\r\n at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\r\n at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()\r\n at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\r\n at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)\r\n at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()\r\n at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)\r\n at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)\r\n at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)\r\n at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)\r\n at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)\r\n at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)\r\n at System.Data.Entity.Internal.EdmMetadataRepository.QueryForModelHash(Func`2 createContext)\r\n at System.Data.Entity.Internal.InternalContext.QueryForModelHash()\r\n at System.Data.Entity.Internal.ModelCompatibilityChecker.CompatibleWithModel(InternalContext internalContext, ModelHashCalculator modelHashCalculator, Boolean throwIfNoMetadata, DatabaseExistenceState existenceState)\r\n at System.Data.Entity.Internal.InternalContext.CompatibleWithModel(Boolean throwIfNoMetadata, DatabaseExistenceState existenceState)\r\n at System.Data.Entity.Database.CompatibleWithModel(Boolean throwIfNoMetadata, DatabaseExistenceState existenceState)\r\n at System.Data.Entity.Database.CompatibleWithModel(Boolean throwIfNoMetadata)\r\n at System.Data.Entity.DropCreateDatabaseIfModelChanges`1.InitializeDatabase(TContext context)\r\n at System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()\r\n at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Cannot attach the file 'C:\\temp\\ADAL.js\\SinglePageApp-AngularJS-DotNet-master\\TodoSPA\\App_Data\\TodoListServiceContext.mdf' as database 'TodoListServiceContext'.","ExceptionType":"System.Data.SqlClient.SqlException","StackTrace":" at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n at System.Data.SqlClient.SqlConnection.Open()\r\n at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)\r\n at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)\r\n at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)\r\n at System.Data.Entity.Core.EntityClient.EntityConnection.<Open>b__2()\r\n at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()\r\n at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\r\n at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)\r\n at System.Data.Entity.Core.EntityClient.EntityConnection.Open()"}}}

**Comment by nigel-dewar** [comment]
Managed to get Chrome working. Had to clear out cache.

But the error with the database initialization is still present. I noticed there is nothing in Web config for database config. How is this web api supposed to create it (the database) then?

**Comment by nigel-dewar** [comment]
Lastly, this is more of a complaint in general. Im new to programming so dont have the ability yet to point out if others work is half ass-ed or not. But my experience over the last six months is all the work I have done with Node and the open source community and projects out there is that it has been such a breeze and a pleasure to learn.

Microsoft stuff is not like that. It is painful, frustrating, and difficult. I used firebase to knock out a beautiful app the other day and it was sooo easy!. Why does all the stuff with ms, its systems and samples have to suck so much. Looking forward to the day it gets it act together.

**Comment by brandwe** [comment]
Thanks for the feedback and I'm sorry you had such a rough time. We are
always trying to improve our documentation. Feel free to email me at
brandon.werner@microsoft.com with any feedback you have about what you
encountered.

**Comment by nigel-dewar** [comment]
Hi Brandon,

 

Im not sure if anything I say can be of any use to you guys there, because I am looking at this from a totally different perspective you guys there at ms.

 

And besides that because I am pissed off , it will likely be more of a rant anyway, but here is my feedback none the less.

 

Quite a few of the examples I have trialled have failed on me in one way or another. For instance with the expense manager app, written by Dan Wahlin, was good and all, and demonstrated the use of the ADAL.NET library to hook into ad, get a token for use with O365 (SP Online). This worked great in Dev on my local machine, but then I tried to load it up on azure, and it failed. The error passed back, I searched and searched, I knew it was an Azure AD error, but could not find how to resolve it. I double checked that I did everything correct, loaded up some different azure projects (with Databases),  loaded them on Azure and all good. So I had the deployment steps correct, but I could not get this thing loaded up for the life of me.

 

I logged an issue against this project on GitHub ad Dan responded back letting know that it was just a sample and that he had not tried to load it on azure. If I ever got it working, then please let him know what was wrong. I’m like ‘WTF!’. Thanks for your help. Useless sample that turned out to be if I can’t even be put in production! 

 

Then Andrew Connell comes along, and redevelops the same app but using ADAL.JS, which is nice, except its written in typescript. I don’t know TS, and from my experience in the node world, not many people are using it. That is fine, I can see that TS gets translated into normal JS. Andrew Connells version of this sample loads up nice on azure which is a Win!  But the way he has written the app is OVERLY complicated. I spent most of a day trying to understand his way of writing angular. I tried to write some angular controllers to add onto his sample (to do my own thing) but got weird errors. I could not understand why as I have been writing quite a bit of angular and have created some working successful apps, so I kind (just kinda) know what I am doing, but I could not work with his stuff. In the end I gave up!  

 

I decided to myself, right, the guys they are hiring at ms to write these samples, I don’t care a rats ass if they are big names, or big shots in the industry, there samples suck and Im going to have to write my own. Its funny because often when I do work away at something and end up understanding it, it makes my realize that a lot of these big shots are completely useless teachers regardless of their rep. I KNOW when I get to the stage when I start teaching people this tech, I will be able to explain it much better, and provide working (tested) examples that demonstrate end to end the technologies in play.

 

So I get this sample attempting to understand ADAL.JS, and it works partially, but not in Chrome. Now I realize stuff does not always work for many reasons, so I figured there must be something wrong with my chrome, which I managed to fix by clearing the cache. But then the web api database (TODO’s) wont load. Its just a friggen joke!

 

As I stated, I started getting serious about programming about 6 months ago. I love node and the open source stuff, and especially firebase. Granted, not everything works, but the reliability, ease of use, ease of learning, ease of getting help pisses all over ms and azure stuff!  I started learning .net, MVC, web api because these are the most commonly known technologies and you assume (wrongly) that because its ms stuff, it would be the best or at least pretty dam near the top. By chance I started playing around with some node stuff, and then a few other things here and there, and started to find, hang on a sec, why is this so much easier to understand. Why is it much simpler to design an api in node than web api? Why is it so much faster?  Then I found firebase, and I think I found the answer. 

 

Don’t worry about pissing around with AutoMapper, Entity Framework, UOW, IOC, and don’t even get me started on .net Identity, man all this crap is a waste of time!!!!   If Microsoft wants to get its act together it needs to look at tools like firebase and parse. But especially firebase coz they got it going on! Simple! Simple! Simple!, Easy to Use! Easy to Use! Easy to Use! Fast!, Fast!, Fast! Good doco, and it works!

 

take Azure, with all its marketing money spent on hyping it up! I friggen hate it. Its painful to use. Lets get real for a tick. I want to develop an api right, to be used for both desktop browser and mobile devices, do I use a standard web app in azure, or do I use a azure mobile services application?  I saw MS released the new app services thing the other day. I spent an hour looking at it all and I was still thinking, so what?  Seems nothing has really improved here.

 

What you need is “1” api backend, 1!!! Singular. Not 2 (1). It should have a slick user interface, it should not be backed by SQL DB, it should be backed by Document DB, or some other noSQL db, but seriously, no SQL, its 2015 for crying out load.

 

You should not struggle to configure Authentication. It should be very simple. You should not have to go to azure AD to piss around in there, setting this that, and everything else. You should not have to go download a manifest file, adjust the oauth implicent flow to ‘true’ and re-upload.

 

I mean seriously!!! Facebook had all this app module and authentification stuff sorted years ago. Why is ms so far behind. I think ms only started supported JWT recently was that not the case?

 

This service MBAAC should be able to be used for ANY app. Desktop, browser, and mobile. The ability to alter the data in the DB should be really simple. The logic behind configuring authz, authn should be easy to understand (visualize) and make sense of. The security rules should be easy and straight forward to configure (firebase). 

 

In fact, if ms takes a good look at firebase, which google now bought, you would see how a back end service ought to look at. Ms should have bought these guys ought. But it seems ms is not very good at identifying talent. No offence to you mate, but it seems they can identify the right tech to spend billions on. Now Google is going to turn this service into something that pisses all over anything azure has to offer. Take a look at their service man! It can really be that hard for ms to develop something life that. Missing out on Angular was another dum move.

 

I think you guys have too many old dogs there, living in the old world. No idea about how modern apps ( and the hosting of them ) needs to look like.

 

No, the MS way is simple a pain in the ass! A real nightmare for app developers to work with, and the only reason why I am even bothering is because I trained in SharePoint and I have to learn this crap. But I tell you what, any chance I get to not use MS, I take it, because its just such a nightmare.

 

You know I found an example of an angular app that worked properly with .net web api using identity. It took me a friggen week to find it. The guy had built an end to end example of using a separated angular front end, that hooked into the web api backend, performed authN, and had some authZ rules so that it provided a full end to end RBAC example. IT working perfectly. I thanks the creator and said I had a nightmare trying to learn or find this info from MS. His response was he felt that same way, hence his blogs slogan was , programming for the real world’  http://oscarmeszar.com/angularjs-webapi-owin-authorizationauthentication-role-based/ 

 

This is the quality of work, and documentation MS needs to get to. None of this half ass BS, that drives everyone spare. Hire some decent friggen people that develop apps ‘for the real world’ and get some end to end examples set up, that are tested ( on Azure ) and provide detailed tutorials. They way its currently been done is stupid.

 

I am working to understand ADAL.js so that I can start to use Azure for only 1 thing, and 1 thing only, to authenticate my apps with my corporate clients, who still use ms products. Otherwise I will be using ANY other technology to develop and host my apps rather than azure. When I run into folk getting into app design these days, they ask me, what to use, I say ‘anything but MS mate, trust me its not worth the pain!’

 

I will figure out this ADAL.js thing, thank you for creating it. Because now I will be able to build my apps, host them on firebase with the backend, authenticate to azure ad, which allows me to do what I need to do. Im able to smooth my customers fears when I say the data is not hosted on azure because I tell them that its hosted on something better, Google servers. And a CDN at that which likely explains why its so ridiculously fast. Once I have perfected using Azure AD, with firebase, I will begin to publish articles far and wide about how to do it, and why one would do it, so as to free app developers from the pain of hosting on azure, and developing apps using web api and other .net crap which is just so ridiculously hard to use and learn for that matter. All is not lost though, O365 is pretty cool, and I will use this for a data source for a lot of corporate clients, but trust me man, anything else, no way.

 

Anyway enough MS bashing. All frustration and anger aside. I believe ms is going in the right direction (finally) but it seriously needs to jack up its ideas about how it provides samples, and make sure its tested ( and runs on Azure )!

 

Redesign the BAAS because the current implementation sucks. Back it with noSQL by default. Massively simplify the authN, authZ functions. And generally stop sucking.

 

This turned out to be a harsh rant. I imagine it will be filed under ‘R’

 

But these are my thoughts. I’ve talked to a few other devs who are quite experienced, and they feel the same way. They have not bothered to touch azure and they stopped using .net ages ago because its just a pain in the ass. But I have been asked to look into adal.js because it interests them greatly, the opportunity to deal with all the brain washed muppets who are still using ms tech ( most businesses unfortunately ), but be able to provide sweet, fast, apps that work great, and great to develop.

 

I wasn’t always like this. I was a real firm MS believer. I spend heaps of money and time learning sharepoint. But these days mate, I realized the little guys have left the new IBM behind and the new IBM is desperately struggling to catch up.

 

If ms took a group of guys and girls out of school. Not with a computer science degree. ( definitely not with a degree ) and gave them six months to learn to program using any tools and services they wished to use. Ms would end up with the answers as to how they need to structure azure and how its development tools ought to work.

 

Cheers Brandon,

 

Nigel D.

**Comment by skwan** [comment]
Nigel, thank you for the feedback.  Can we contact you later, to review some of our go forward ideas?

**Comment by nigel-dewar** [comment]
Hi Stuart,

 

Look I appreciate you guys being so awfully nice about it, considering my harsh feedback. But it is pointless pandering to my ego because I have none.

 

There are a million developers who are highly skilled whom can give you the reviews on your ideas you want. I am just a beginner in development hence my onions will be very one sided as they lack insight. If you wish to delete my post then feel free too. You have my feedback.

**Comment by skwan** [comment]
Actually, we just wanted to review some of our ideas with you so we could get a beginner's perspective on them.  But thanks again for the feedback.  Our goal is to advance the state of the art for identity management as a service, and every point of view counts.
