### ISSUE TITLE
Not working on IE8

### ISSUE THREAD

**Issue by AbdoDabbas** [AzureADSamples/SinglePageApp-AngularJS-DotNet#18]
This sample doesn't work on IE8, as I figured out that it's ADAL which is causing the problem, any solution for this ?

**Comment by dstrockis** [comment]
Hey @AbdoDabbas... What's the behavior you're seeing? Does the sample not run? Does the login redirect fail? Is there any error in the console?

**Comment by AbdoDabbas** [comment]
There's an error in the console saying that Angular is not defined or something, it's like angular object is not defined at all, problem shows only when using ADAL with Angular in IE8, when using it with another browser it works great, you can try the sample your self and make sure.

**Comment by dstrockis** [comment]
@weijjia or @anujc do you have an easy way to test this out?  I can't install IE 8 on my box, and I'd like to avoid spinning up a VM if possible.

**Comment by AbdoDabbas** [comment]
Sorry for that but I was in a middle of a project and faced this problem which will let me search for another library instead of ADAL which (as I searched till now) is not an easy thing to do using another library, Thanks for replying

**Comment by AbdoDabbas** [comment]
If you just Used IE11 and pressed F12 then go to Emulation -> Document Mode = 8 
This is enough to see the problem, you don't need to install IE8 to show it.

**Comment by dstrockis** [comment]
Thanks. I get the same error in the sample whether or not I include ADAL in the project - so I don't think it's a problem with the library - rather, the sample wasn't written to support Angular with IE8.

I could attempt to add support for IE8 to the sample - but I'd rather not add any IE8 specific code that might seem strange to those readers using Firefox, Chrome, IE11, etc.  I hope that seems reasonable.  On first glance it seems there are some decent help articles out there for getting Angular to work in IE8.

**Comment by AbdoDabbas** [comment]
But it's surly a problem with ADAL library, I'm so sure, I'm using it in another project.
Make sure please that Angular version is less than 1.3 because it'll not support IE8 any way.
I'm using Angular with the another project with version 1.2.28and it's working perfectly, but adding ADAL crashed it.
Any way if you can help me with ADAL that would be great.

**Comment by AbdoDabbas** [comment]
You can try it with a plain HTML
just include Angular and the ADAL with very simple app.js

**Comment by dstrockis** [comment]
Sorry, I don't have time at the moment to investigate this.  Since you're confident this is a library issue, I'm going to close this issue and we can continue investigating on the other issue you opened on the library repo.

**Comment by dstrockis** [comment]
Duplicate: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/144
